COMMONMAKEFILE=../../../Makefile.common
SRCS = 
OTHER =
OTHER += Makefile
OTHER += ast.html
OTHER += command.html
OTHER += conf.html
OTHER += confadmin-advanced.html
OTHER += conferences.txt
OTHER += db.html
OTHER += debug.html
OTHER += eval.html
OTHER += getconfs.html
OTHER += index.html
OTHER += meetmeadmin.html
OTHER += monitor.html
OTHER += monkey.html
OTHER += msg.html
OTHER += mute.html
OTHER += namespaces.html
OTHER += props.html
OTHER += putconfs.html
OTHER += server.html
OTHER += system.html
OTHER += validate.html
OTHER += webusers.html

include $(COMMONMAKEFILE)

SUBDIRS= 
